import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import utilsStyles from "./utils.module.css";
import Link from "next/link";
import Image from "next/image";

const name = "Muhammmad Ramzan";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <header className={styles.header}>
            <Link href="/">
              <Image
                priority
                src="/images/profile.jpeg"
                className={utilsStyles.borderCircle}
                height={108}
                width={108}
                alt=""
              />
            </Link>
            <h1 className={utilsStyles.heading2Xl}>{name}</h1>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
